version: '3'

services:
  svelte-app:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ./env.local:/usr/src/app/.env
    command: ['bun', 'run', 'dev']
